### ISSUE TITLE
P4G PC Font width editing error

### ISSUE THREAD

**Issue by reishikin** [Meloman19/PersonaEditor#12]
I want to try edit the width of various glyphs but when I try to double click to edit the width, it opened up a blank page without anything to edit. I believe it's a bug or P4G PC font is not supported.
<img width="563" alt="Screen Shot 06-18-20 at 09 36 PM 001" src="https://user-images.githubusercontent.com/67111277/85034187-01264d00-b1ac-11ea-8f79-24938a8051fa.PNG">

**Comment by Meloman19** [comment]
Fixed it.
