### ISSUE TITLE
Не читает .spr с pc версии

### ISSUE THREAD

**Issue by kurigohan0** [Meloman19/PersonaEditor#13]
Не читает .spr, а вместе с этим не работает редактор. 

Есть отличия в заголовке файлов
Слева пк версия, справа вита (выделен filesize из SPRHeader)
![image](https://user-images.githubusercontent.com/32684277/85199564-342a2700-b2f9-11ea-8cff-8a81cd6a5b96.png)

И вот здесь срабатывает исключение
![image](https://user-images.githubusercontent.com/32684277/85199619-aa2e8e00-b2f9-11ea-8f61-f744c039929c.png)

Короче без этого невозможно редактировать координаты спрайтов, памаги

пкшный .spr: https://drive.google.com/file/d/1rDxcbDUo9-rrb0dwkklttsFP8AK8edr2/view?usp=sharing
виты: https://drive.google.com/file/d/1QRUUP_-_1UjSBVLFhEz4mO5PvT49JYqk/view?usp=sharing

**Comment by Meloman19** [comment]
Для запаковки лучше пока использовать это же приложение. Amicitia теряет полупрозрачность.

**Comment by kurigohan0** [comment]
Понял, спасибо!
