### ISSUE TITLE
Persona 4 Golden Japanese Text Edit

### ISSUE THREAD

**Issue by Dlon93** [Meloman19/PersonaEditor#15]
Hello, 

Thank you for this wonderful tool. I have a quick question. I would like to edit the Japanese text of the Persona 4 Golden PC version, but when I try to open those event files with your editor, the Japanese characters are not displayed like the English text is, but are instead displayed like, well, this: �����������. 

Do you think this program will ever support editing Japanese files?

In any case, thank you!

Dlon93

**Comment by Meloman19** [comment]
@Dlon93 Program is support editing of any files of any language. Just need font and encoding.

Just get last release of app (I updated this) and during editing select a font P4_PC.

**Comment by Dlon93** [comment]
> @Dlon93 Program is support editing of any files of any language. Just need font and encoding.
> 
> Just get last release of app (I updated this) and during editing select a font P4_PC.

Yes, it works. Thank you! Finally, I've been trying with different tools for days now.
Thank you so much!!!
