### ISSUE TITLE
Script request for exporting as an excel table

### ISSUE THREAD

**Issue by Wilrick-P4** [Meloman19/PersonaEditor#17]
Hi Meloman19 !

I'm a part of the Persona 4 Golden French Translation Team, we are using Persona Editor on our project and I'm trying to contact you because we need your help on something that could skip hours of work for us ^^

The first step of work is preparing the script scenes for our translators. We copy-paste the script scenes and copy them into an Excel table template we made. So basically we make this : 

![image](https://user-images.githubusercontent.com/67701731/88307699-8e5d4400-cd0c-11ea-9624-3fd3f088fbe3.png)

Into this : 

![image](https://user-images.githubusercontent.com/67701731/88307829-aaf97c00-cd0c-11ea-9456-397734cc7a0f.png)

It is a really time-consuming task that does not require much human thought. We were wondering if it was possible to make a script to convert the .ptp into Excel sheets right of the bat. It would save us so much time. Since we don't know a lot about the .ptp format, we can't do it without your help. Can you help us ? 

Answer me here or on Discord please. My user name is Wilrick#0925 👍  Thanks in advance !

**Comment by Meloman19** [comment]
Go to Discord.
