### ISSUE TITLE
How about mask in .bat for all files?

### ISSUE THREAD

**Issue by makc-ar** [Meloman19/PersonaEditor#2]
Hi **Meloman19**!
**Example to plain files:**
for /R %%a in (*.fnt) do .\Tools\PersonaEditor.exe -expimage "%%a"
**or**
for /R %%a in (*.fnt) do .\Tools\PersonaEditor.exe -expimage "%%a" "%%~pna.png"
**or**
SETLOCAL ENABLEDELAYEDEXPANSION

for /r %%i in (*.fnt) do ( 
  set fdir=%%~dpi
	.\Tools\PersonaEditor.exe -expimage "%%i" "!fdir:~0,-1!" 
)

**Example for container**
for /R %%a in (*.pac) do .\Tools\PersonaEditor.exe -expall "%%a"
**or**
for /R %%a in (*.pac) do .\Tools\PersonaEditor.exe -expall "%%a" "%%~dpna"

Do you speak Russia?

**Comment by Meloman19** [comment]
Говорю.
Только зачем тебе маска, если ты и так можешь свои примеры использовать?)

Для обычных файлов:
**for /R %%a in (*.fnt) do (.\Tools\PersonaEditor.exe "%%a" -expimage)**

Для контейнеров:
**for /R %%a in (*.pac) do (.\Tools\PersonaEditor.exe "%%a" -expall)**

**Comment by makc-ar** [comment]
Понял, ключ надо было вынести. Наша команда хочет перевести эту игру на русский язык. А как полностью распаковать все контейнеры и файлы у игры вплоть до текстов, а вторым батником собрать обратно? Я потом хочу залить текст на платформу http://notabenoid.org для перевода, а текстуры передать художнику.

**Comment by Meloman19** [comment]
Какую игру-то? 5 персону?
Ну с текстурами я почти не соприкасался и разбирал только содержащие текст форматы. Плюс у PS3 текстуры в своих форматах хранятся и думаю кто-то другой уже их разобрал - на Amicitia нужно повнимательней смотреть.
И почему напрямую-то со мной не связались? На ZoG уже давали предложение начать: текст я уже вытащил.

**Comment by makc-ar** [comment]
Ага, про неё писал, там в основном текстуры в .dds, но я хотел ещё все контейнеры извлечь для просмотра. А запаковку TMX будешь добавлять? Давай в скайпе обсудим движения? Я - makc_ar, т.е. ник в скайпе. У меня не получается текст дропать, т.е. все текстовики пустые идут, yаверное, я что-то не то в консоли делаю, к примеру:
for /R %%a in (*.BMD) do (.\Tools\PersonaEditor\PersonaEditor.exe "%%a" -expptp /sub)
for /R %%a in (*.PTP) do (.\Tools\PersonaEditor\PersonaEditor.exe "%%a" -exptext /sub)
