### ISSUE TITLE
Cannot open P3D PS4 .FNT file in the program  

### ISSUE THREAD

**Issue by DniweTamp** [Meloman19/PersonaEditor#22]
Vita's font_p3.fnt opens in the program just fine, and I can export or edit it too, meanwhile PS4's version of this file doesn't even open there.

I've attached the PS4 file if you want to take a look
[font_p3.zip](https://github.com/Meloman19/PersonaEditor/files/5448187/font_p3.zip)

**Comment by Meloman19** [comment]
cddfad1aa5a1f3731fa374b7d4e5a3d8862e203e
@DniweTamp try last version
