### ISSUE TITLE
Add a license to the repo. 

### ISSUE THREAD

**Issue by monyarm** [Meloman19/PersonaEditor#23]
I'm working on NovelVM, à visual novel reimplementation project, I'm currently working on the persona games, and would like to make use of your fnt reading code, but as NovelVM is gpl licensed, I can't use your code unless it has a license.

**Comment by Meloman19** [comment]
@monyarm I hope the MIT license suits you?

**Comment by monyarm** [comment]
It would. Thank you.

**Comment by Meloman19** [comment]
Nice.
