### ISSUE TITLE
File replacement not working for msg.

### ISSUE THREAD

**Issue by dgsmiley18** [Meloman19/PersonaEditor#24]
![image](https://user-images.githubusercontent.com/38007632/117487897-10d48e80-af42-11eb-919f-d907a9ce2cd3.png)
I don't know why i can't replace this .msg with my new .msg edited.
Game: Persona 4 Golden.

[Msg.zip](https://github.com/Meloman19/PersonaEditor/files/6443421/Msg.zip)

**Comment by Meloman19** [comment]
@dgsmiley18  
How did you get your new .msg? As can I see this .msg with broken structure.
Please, write the basic steps.
