### ISSUE TITLE
Add P3P & P4G Simplified Chinese / Japanese / Korean FNT&FNTMAP supports

### ISSUE THREAD

**Issue by EditorKos** [Meloman19/PersonaEditor#37]
Since there's no Simplified Chinese fntmap files for P3P & P4G .fnt in the tool yet, using PersonaEditor to show bmd texts from .bf files will result in no corresponding encoding, causing Mojibake. Thankfully P3P has the same font mapping table with P4G (only one word character different lol), so I decided to create both ones to help anyone have the same problem. Maybe @Meloman19 can update the release with these.

Newest update: Also made ones for P3P & P4G Japanese / Korean FNT & FNTMAP files. Now the download link will contain all 3 languages FNT & FNTMAP files.

[font_(CHS+JP+KR).zip](https://github.com/user-attachments/files/16678782/font_.CHS%2BJP%2BKR.zip)

For now if anyone wants to use it, put the FNT and FNTMAP files all in "font" folder.

**Comment by Meloman19** [comment]
Thank you. Updated. See 1.6.2 version.

**Comment by EditorKos** [comment]
https://github.com/Meloman19/PersonaEditor/issues/32

@Meloman19 Thank you for adding! There's also a Traditionl Chinese one that I made year ago.
