### ISSUE TITLE
Request: P3D/P5D Support for PersonaFont

### ISSUE THREAD

**Issue by ShrineFox** [Meloman19/PersonaEditor#5]
https://cdn.discordapp.com/attachments/144214416014049281/485563045565825045/font_p5.fnt
https://cdn.discordapp.com/attachments/144214416014049281/485563070907809803/font_p3.fnt

**Comment by Meloman19** [comment]
> https://cdn.discordapp.com/attachments/144214416014049281/485563045565825045/font_p5.fnt
> https://cdn.discordapp.com/attachments/144214416014049281/485563070907809803/font_p3.fnt

[Test](https://github.com/Meloman19/PersonaEditor/releases/)
