### ISSUE TITLE
Can't insert PNG to FNT

### ISSUE THREAD

**Issue by Adam-Saeed** [Meloman19/PersonaEditor#6]
When I try to insert a png to the font it won't change anything.
Even when I tried to insert an exported png from the Russian to my font nothing changed too.

**Comment by Meloman19** [comment]
> When I try to insert a png to the font it won't change anything.
> Even when I tried to insert an exported png from the Russian to my font nothing changed too.

How do you do that? You need:
1) Open FNT
2) Right Click ->Replace
3) Select .png filter and open PNG file
4) File -> Save As

If it does not work, then send FNT and PNG.

**Comment by Adam-Saeed** [comment]
[font.zip](https://github.com/Meloman19/PersonaEditor/files/2427024/font.zip)

**Comment by Meloman19** [comment]
The problem was in right-to-left character on filename. Fixed.
[There](https://github.com/Meloman19/PersonaEditor/releases/latest)
