### ISSUE TITLE
How to import and export the files?

### ISSUE THREAD

**Issue by JackScarlet** [Meloman19/PersonaEditor#7]
how to import and export the files using this tool?
If it was not possible, how do I add this option?

**Comment by Adam-Saeed** [comment]
to export just right-click on the file you want in PersonaEditor and select "save as" then change the format to what you want like PNG, and for import right-click again on your file and select "replace"

**Comment by Adam-Saeed** [comment]
+ you have to click "File" > "Save as" in order for change to happen, because sometimes the program won't update the preview (in the older versions).
